### ISSUE TITLE
Version 1.0 Checklist

### ISSUE THREAD

**Issue by scott-m-sarsfield** [scott-m-sarsfield/covert-villain#5]
Features / Fixes
- [x] Fix leaveGame logic (shouldn't crash if someone leaves on Game Over screen)
- [x] Presidential Power: Investigate Loyalty (Party)
- [x] Presidential Power: Special Election
- [x] Concurrency test: if 2 people vote at same time, will both votes be recorded, or will a "last in wins" situation occur?
- [x] Cache-busting between deploys?
- [x] Re-theme to generic / Star Wars @kennethbigler 
- [x] Rename to `covert-villain` (+ reset prod env)
- [ ] Auto-generate codes for host?
- [x] Auto-capitalize room codes for participants
- [ ] Replace logo

Chores
- [x] Include a README ('cause how the heck do I even get this to work on my machine?)

Someday / Maybe
- [x] Move from styled-components to something less HOC-y
- [ ] More unit tests?
- [ ] TypeScript?
- [ ] Object Storage instead of Postgres?
- [ ] yarn lint script?
